name: Build Community Annotation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }} community builder"

    strategy:
      fail-fast: true
      matrix:
        perl-version:
          - "5.26"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: install cpm and multiple modules
      uses: perl-actions/install-with-cpm@v1.3
      with:
        cpanfile: "cpanfile"
        sudo: false

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O bedToBigBed http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
    
    - name: chmod bedToBigBed
      run: chmod +x bedToBigBed

    - name: Add current directory to path
      run: echo "::add-path::."
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Run the Perl reformatter
      run: perl reformat_ucsc_annotation.pl
    
    - uses: actions/upload-artifact@v2
      with:
        name: UCSC Community BigBed
        path: ucsc_annotations.bb
