name: Build Community Annotation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: install cpm and multiple modules
      uses: perl-actions/install-with-cpm@v1.3
      with:
        cpanfile: "cpanfile"
        sudo: false

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
